### ISSUE TITLE
ModuleNotFoundError for module 'dtpattern.services'

### ISSUE THREAD

**Issue by rsgoncalves** [jumbrich/dtpattern#1]
* dtpattern version: 0.1.2
* Python version: 3.6
* Operating System: macOS 10.12.6

### Description

I was trying to run the latest state of the code, but encountered a ModuleNotFoundError. Am I missing some installation step?

### What I Did

```
python setup.py install

dtpattern items 123 12 1

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/dtpattern", line 11, in <module>
    load_entry_point('dtpattern==0.1.2', 'console_scripts', 'dtpattern')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dtpattern-0.1.2-py3.6.egg/dtpattern/cli.py", line 10, in <module>
    from dtpattern.services.cli_dtpattern import dtpattern
ModuleNotFoundError: No module named 'dtpattern.services'
```

**Comment by jumbrich** [comment]
Fixed
